# .github/workflows/ci-cd.yml
name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: docker build -t myapp:latest .
      - name: Push Docker image
        run: docker push myapp:latest
      - name: Deploy to Kubernetes (AWS)
        run: kubectl apply -f k8s/aws/deployment.yaml
        env:
          KUBECONFIG: ${{ secrets.AWS_KUBECONFIG }}
      - name: Deploy to Kubernetes (Azure)
        run: kubectl apply -f k8s/azure/deployment.yaml
        env:
          KUBECONFIG: ${{ secrets.AZURE_KUBECONFIG }}

